version: "3.8"
services:
  rootdb:
    env_file:
      - env
    image: rootdbapp/rootdb:dev
    container_name: rootdb
    restart: unless-stopped
    stdin_open: true
    tty: true
    working_dir: /var/www/
    volumes:
      - ${API_ENV_PATHNAME}:/var/www/api/.env:rw
      - ${FRONTEND_APP_CONFIG_PATHNAME}:/var/www/frontend/app-config.js:rw
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      LARAVEL_WEBSOCKETS_PORT: "${LARAVEL_WEBSOCKETS_PORT:-6001}"
      TIMEZONE: "${TIMEZONE:-Europe/Paris}"
      NGINX_USE_SSL: "${NGINX_USE_SSL:-0}"
      NGINX_API_PORT: "${NGINX_API_PORT:-80}"
      NGINX_API_HOST: "${NGINX_API_HOST:-localhost}"
      NGINX_WS_API_PORT: "${NGINX_WS_API_PORT:-80}"
      NGINX_WS_API_HOST: "${NGINX_WS_API_HOST:-localhost}"
      NGINX_FRONTEND_PORT: "${NGINX_FRONTEND_PORT:-80}"
      NGINX_FRONTEND_HOST: "${NGINX_FRONTEND_HOST:-localhost}"
    ports:
      - "${NGINX_API_PORT:-80}:${NGINX_API_PORT:-80}"
      - "${NGINX_WS_API_PORT:-80}:${NGINX_WS_API_PORT:-80}"
      - "${NGINX_FRONTEND_PORT:-80}:${NGINX_FRONTEND_PORT:-80}"
    networks:
      rootdb-network:
        ipv4_address: 172.200.0.10
    depends_on:
      - rootdb-memcached
      - rootdb-db-api

  rootdb-memcached:
    image: rootdbapp/rootdb-memcached:latest
    container_name: rootdb-memcached
    tty: true
    restart: unless-stopped
    ports:
      - "${MEMCACHED_PORT:-11211}:${MEMCACHED_PORT:-11211}"
    networks:
      rootdb-network:
        ipv4_address: 172.200.0.20

  rootdb-db-api:
    image: mariadb:latest
    container_name: rootdb-db-api
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    environment:
      MYSQL_TCP_PORT: ${DB_PORT:-3306}
      MYSQL_UNIX_PORT: ${DB_PORT:-3306}
      MYSQL_DATABASE: rootdb-api
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-oLoo4cee5aaYon4po6ojoophie2aiY}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD:-uo2Coxiek4chaib5apooqu6yei8ip1}
      MYSQL_USER: rootdb_api_user
      SERVICE_TAGS: prod
      SERVICE_NAME: mariadb
    volumes:
      - ${DB_DATA_DIR:-rootdb_db_api_var_lib_mysql}:/var/lib/mysql
    networks:
      rootdb-network:
        ipv4_address: 172.200.0.30

volumes:
  rootdb_db_api_var_lib_mysql:

networks:
  rootdb-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.200.0.0/16





