FROM debian:12-slim

RUN apt update \
    && apt install -y locales wget ca-certificates apt-transport-https software-properties-common wget curl lsb-release sudo bzip2 bsdextrautils \
    && rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
    && wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver \
    && chmod +x /usr/local/bin/semver \
    && curl -sSL https://packages.sury.org/php/README.txt | bash -x \
    && apt install -y memcached mariadb-server php8.2 php8.2-gd php8.2-bcmath php8.2-dom php8.2-fpm php8.2-iconv php8.2-mbstring php8.2-memcached php8.2-curl php8.2-mysql php8.2-pgsql php8.2-zip nginx postgresql-client-common supervisor


ENV LANG en_US.utf8
