FROM bitnami/minideb:latest

LABEL \
	org.opencontainers.image.authors="atomicWeb SAS" \
	org.opencontainers.image.description="A self-hosted reporting application" \
	org.opencontainers.image.documentation="https://documentation.rootdb.fr/" \
	org.opencontainers.image.licenses="Propriatery" \
	org.opencontainers.image.source="https://github.com/atomicweb-sas/rootdb/blob/main/docker/Dockerfile_rootdb" \
	org.opencontainers.image.title="Base image for RootDB" \
	org.opencontainers.image.url="https://www.rootdb.fr/" \
	org.opencontainers.image.vendor="atomicWeb SAS" \
	org.opencontainers.image.version="$VERSION"

RUN install_packages ca-certificates curl apt-transport-https software-properties-common wget  lsb-release \
    && curl -o /usr/local/bin/semver "https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver" \
    && mkdir -p /etc/nginx/conf.d.tpl \
    && chmod +x /usr/local/bin/semver \
    && curl -sSL https://packages.sury.org/php/README.txt | bash -x \
    && install_packages \
    memcached \
    bzip2 \
    gawk \
    iputils-ping \
    iproute2 \
    jq \
    mariadb-client \
    nmap \
    nginx \
    procps \
    php8.2 \
    php8.2-curl \
    php8.2-dom \
    php8.2-fpm \
    php8.2-iconv \
    php8.2-mbstring \
    php8.2-memcached \
    php8.2-mysql \
    php8.2-pgsql \
    postgresql-client-common \
    supervisor \
    unzip


COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d.tpl /etc/nginx/conf.d.tpl

COPY supervisor/supervisord.conf /etc/
COPY supervisor/supervisor.d /etc/supervisor.d/

COPY php-fpm/8.2/fpm/pool.d/www.conf /etc/php/8.2/fpm/pool.d/www.conf
COPY php-fpm/8.2/fpm/php.ini /etc/php/8.2/fpm/php.ini
COPY php-fpm/8.2/fpm/php-fpm.conf /etc/php/8.2/fpm/php-fpm.conf
COPY php-fpm/8.2/cli/php.ini /etc/php/8.2/cli/php.ini
COPY php-fpm/sourceguardian_loader_14.0.1/ixed.8.2.lin /usr/lib/php/20220829/ixed.8.2.lin
